spring:
  application:
    name: swiftboot-demo
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/swiftboot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
    open-in-view: false
logging:
  level:
    root: INFO
    org.swiftboot: DEBUG
swiftboot:
  web:
    filter:
      cors: true
    validation:
      resultInJson: false
  data:
    model:
      autoGenerateId: true
      initData: true
      initBaseDir: init
      initBaseDaoPackages:
        - org.swiftboot.demo.model.dao
      initBaseEntityPackages:
        - org.swiftboot.demo.model.entity
  service:
    redis:
      host: localhost
      port: 6379
  auth:
    enabled: true
    session:
      storageType: redis
      tokenKey: swiftboot_token
      expiresIn: 0