http:
  client:
    connect:
      # http 客户端链接超时时间
      timeout: 2000
    socket:
      # http 客户端socket超时时间
      timeout: 10000
swiftboot:
  web:
    filter:
      cors: true
#      # 跨域允许的范围
#      corsAllowOrigin: 'localhost'
#      # 允许的头
#      allowHeaders:
#        - sso_token
#        - my_header
    validation:
      # 是否输出json格式的校验结果，否则直接输出为字符串拼接
      resultInJson: false
    formatPatternLocalDateTime: yyyy-MM-dd HH:mm:ss
    formatPatternLocalDate: yyyy-MM-dd
    formatPatternLocalTime: HH:mm:ss
    formatPatternYearMonth: yyyy-MM
    formatPatternMonthDay: MM-dd
  data:
    model:
      # 是否自动生成实体类的 ID
      autoGenerateId: true
